### ISSUE TITLE
RxNorm does map RxCUI 435 to the level of interest

### ISSUE THREAD

**Issue by beelahkay** [nt-williams/rxnorm#7]
For RxCUI, there are 2 ATC classes. There is a bug in the package when it comes to parsing those ATC codes into the level of of interest. This is true for other RxCUI with multiple ATC classes as well.

**Comment by nt-williams** [comment]
Fixed with commit 51e8b47

```
> get_atc(435, "third")
[1] "adrenergics, inhalants"       "adrenergics for systemic use"
```
